### ISSUE TITLE
Missing numerous Javascript files and PHP includes

### ISSUE THREAD

**Issue by nailliK** [webcliq/Cockpit_Collections#1]

**Comment by webcliq** [comment]
Thank you for try it out and letting me know about the problem. The Collections module is part of a bigger project of module enhancements to Cockpit, that I want to do. Thus I had arranged that each Module would get its javascript files from a central source. 

Silly me!   I publish just one of the modules without making it run standalone. I have now included the missing JS files in the Cliq JS Library file and the system behaves itself.

I also thought about how a developer who is relatively new to CockPit and/or DataTables would progress once Cliq Collections was in place. The result is that I have added an Installation Tip to the ReadMe. I sincerely hope this helps.
